MODULE P3D_SKEL_IDL
DESCRIPTION IDL wrapper of Pore3D Library - Skeletonization Tools
VERSION 1.0
SOURCE Sincrotrone Trieste S.C.p.A.
BUILD_DATE JAN 2011

FUNCTION	P3DGVFSKELETONIZATION		1	1   KEYWORDS
FUNCTION	P3DLKCSKELETONIZATION		1	1   
FUNCTION	P3DPKSKELETONIZATION		1	1  
FUNCTION	P3DSKELETONANALYSIS			2	2   KEYWORDS
FUNCTION	P3DSKELETONANALYSISFEASIBILITY		2	2   
FUNCTION	P3DSKELETONLABELING			1	1  
FUNCTION	P3DSKELETONPRUNING			1	1   KEYWORDS
